@echo off
echo Starting Helix Backend...
start cmd /k "cd /d C:\Users\93rob\OneDrive\Documents\GitHub\helix-protocol && uvicorn dashboard.backend.main:app --reload --port 8000"
echo Starting Helix Frontend...
start cmd /k "cd /d C:\Users\93rob\OneDrive\Documents\GitHub\helix-protocol\dashboard\frontend && npm start"
exit
